services:
  nginx:
    image: "nginx:1.27.0-alpine"
    restart: always
    working_dir: /app
    links:
      - php-fpm
    volumes:
      - ".:/app"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8089:80"

  php-fpm:
    build: docker/php-fpm
    restart: always
    working_dir: /app
    links:
      - mysql
    volumes:
      - ".:/app"
      - "./docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini"
    environment:
      XDEBUG_MODE: "coverage"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "33306:3306"